### PR TITLE
Support checking whether a domain points at a GitHub Pages IP address

### PR DESCRIPTION
**Pull request by jdennes**
Adds the ability to check whether or not a domain is pointed at a GitHub Pages IP address.

```
› script/console
+ bundle exec pry -r ./lib/github-pages-health-check
[1] pry(main)> check = GitHubPages::HealthCheck.new("getbootstrap.com")
=> #<GitHubPages::HealthCheck @domain="getbootstrap.com" valid?=true>
[2] pry(main)> check.pointed_to_github_pages_ip?
=> true
[3] pry(main)> check = GitHubPages::HealthCheck.new("example.com")
=> #<GitHubPages::HealthCheck @domain="example.com" valid?=false>
[4] pry(main)> check.pointed_to_github_pages_ip?
=> false
```

Based on:

```
› dig getbootstrap.com
;getbootstrap.com.		IN	A
getbootstrap.com.	60	IN	A	192.30.252.153

› dig example.com
;example.com.			IN	A
example.com.		60	IN	A	93.184.216.34
```

Would be grateful for any feedback/suggestions.

/cc @benbalter @spraints @tekkub

### CODE REVIEW

**Comment by benbalter** [comment]
:+1:. I could have sworn we exposed pages IPs through [the meta API](https://api.github.com/meta), but I guess not.

**Comment by tekkub** [comment]
@benbalter nope, but I don't think we want to rely on that here anyway.  If we change IPs around again in the future, we'll need to be able to tell people when they have their DNS set for the old IPs (this is why `LEGACY_IP_ADDRESSES` exists and is hard-coded).  I think it makes sense to hard-code the current IPs in as well, if we make a change in the future it will be a very deliberate action.  It's not something I think we'd be doing frequently anyway.

**Comment by spraints** [comment]
:+1:

**Comment by jdennes** [comment]
@benbalter Would you like to cut a new release?

**Comment by jdennes** [comment]
> Would you like to cut a new release?

Actually, we should wait for https://github.com/github/pages-health-check/pull/15.

**Comment by spraints** [comment]
>> Would you like to cut a new release?

> Actually, we should wait for #15.

#15 is merged, so I think we're ready for a new release?

**Comment by benbalter** [comment]
@tekkub makes total sense. Thanks for walking through it with me.

Cutting a new release now.

**Comment by benbalter** [comment]
:boom: https://github.com/github/pages-health-check/releases/tag/v0.3.0

**Pull request merged**
